---
- name: Создание директории для данных MinIO
  file:
    path: "{{ minio_data_dir }}"
    state: directory
    mode: 0755

- name: Запуск контейнера MinIO
  docker_container:
    name: minio
    image: minio/minio:latest
    pull: yes
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "{{ minio_data_dir }}:/data"
    env:
      MINIO_ROOT_USER: "{{ minio_root_user }}"
      MINIO_ROOT_PASSWORD: "{{ minio_root_password }}"
    command: server /data --console-address :9001
    restart_policy: unless-stopped

- name: Создание systemd-сервиса для MinIO
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
  notify: Перезагрузка systemd и перезапуск MinIO

- name: Включение и запуск сервиса MinIO
  service:
    name: minio
    enabled: yes
    state: started
