- name: Debian postinstall playbook
  hosts: "{{ target_hosts | default('all') }}"
  become: true

  roles:
    #    - common_setup/postinstall
    # - services/coredns
    # - services/minio-docker
    - services/tf-install
