---
# tasks file for debian_afterinstall/roles/tf-install
- name: Установка Terraform 1.6.6 на Debian 12
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Установить зависимости
      apt:
        name:
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Скачать Terraform {{ terraform_version }}
      get_url:
        url: "{{ terraform_url }}"
        dest: "{{ download_dir }}/{{ terraform_zip }}"
        mode: '0644'

    - name: Распаковать Terraform
      unarchive:
        src: "{{ download_dir }}/{{ terraform_zip }}"
        dest: "{{ download_dir }}"
        remote_src: yes

    - name: Переместить бинарник terraform в /usr/local/bin
      copy:
        src: "{{ download_dir }}/terraform"
        dest: /usr/local/bin/terraform
        mode: '0755'
        remote_src: yes

    - name: Проверить версию Terraform
      command: terraform version
      register: terraform_version_output

    - name: Показать установленную версию
      debug:
        msg: "{{ terraform_version_output.stdout }}"